language: node_js
node_js:
  - '8'
branches:
  only:
    - dev
env:
  global:
    - secure: wILZm5K4phsUAe0zmqHP3wMIVCq15HpyUcasPXsDdkZ2k2cyKj6JfjOuLELHA5CRHaYO1mBwUPCV7GOn0w9QAsmnhWNTaqFea0eA2d48vPYs5OYLJhE1zVKf0YXljWs0Wo/uFUVqp+NGmcP3izjQbYiantCWOO+ND+c9SDoFHBQnHGtw4GB1lfucmLMKT3u8bc2cgFpHahIsntns3w1wMgrRmPSZdIpUaPZn4uI35iSP4uVayTx9uli1BgvZqPmO007qCFgogyEOsLIE8ktjEj6NPT/05OHJhHw5X5u6aDP3YKByaQScQHJ4TCbdxMv6p8IFBXMS/3uYLF11/1gOQE2J9QPjBD+moD6vgam/OtPnoAetLFQzzcK2Aw5+L36DiYOYnwnG/mFWqCECxZzOy56+7Xvf4H8ontd38wL2WfujKoC9894AdxNl1AxFKGI5JkPB272glMtrlUlQHh7RJdpIRMVkaQAz4Tl5hoQN9l1jRiVBfDmPS86RMiKGKsQe9nq0VoACs1lg+O57Iza/zbvqZCq/zzdI/rEz+R0YEdzgqgpKlspvRdt4p7w7g8ZUKBp6k9wWnHIkrU+WgCg8SO+wVG1cbU+5LdsgC+Tmjk1oUb+GiTvw12fsc3NE77mKelZ+CnYg5EHwso9RaEQT9GAVcXTKnTsoNRN9ybBHcxQ=
    - secure: PLDJhQbCwiOMMy7jdbo1ZZIhFSIia3OeIm8H8PewRz3W5T41MwaI0Frx3WlYLHyN3Ur0SHmwo7IVfZ7fpGSDcvq07M/jJYetQ7+GNJrvqRonqg6fUw7CnozK5j4bIY45ZpM6jHxyzmQ8Sd7DWBsSfFwk/FDeUF2Hs1ol6Kuz3nc1eNNsbyftun1t25lHHHwIyw7zbrKsV1/P2CsC1pggjA7DdTJgkULvYkBqL8lkp2zfvojz2L8cpx2BConSnW0fb5ZgAxGt4WiV7+sGvR3EmczM3CGEOg0RUBBs7A1ztOd23fNB0lpXieBEi8XzaEVxuP8g8Br4BaboF90ky5BE7i/47eWVkVsNlXj9qdlhJzrTUYLU4Q0+OcNgKHX81rxoyElyD90zIpvG49Qe9v67quc5IKyYc/f4huQdrtAFubJk0AgaRbckX1B8oVDW2T5gJTPsUM3ZmLm40dRMLMxgImYQnAhByOnREMjmYSuSn3/uosJjPijO6kWxRXXLLkn/tSiCiRm500R1zBfmhimps0KfMig/Dss0KWdwfbRH/SKjAIEm+X5seZjhH2XmGl6qhp4cSNl/K9ZJCbIi69juuMdZXNcMVW6CgJ2vRABu9GPPF/7mwanCw/wMQ1Jl4NkL2Gni9s3Yi3OCnVkdFL5lukMtfnd4Eds0/6zuOzd3ATA=
    - NOW_TEAM=itis-4440
    - NOW_NAME=tasklog
    - ROOT_URL=https://tasklog.now.sh
install:
  - npm install --global now
script:
  - now remove $NOW_NAME --safe --yes --token=$NOW_TOKEN --team $NOW_TEAM
  - now deploy --docker --public --name $NOW_NAME --env MONGO_URL=$MONGO_URL --env ROOT_URL=$ROOT_URL --token=$NOW_TOKEN --team $NOW_TEAM
  - now alias --token=$NOW_TOKEN --team $NOW_TEAM
